### ISSUE TITLE
Evil background tasks

### ISSUE THREAD

**Issue by 0xNacho** [voghDev/git-pushdemont#10]
It should also run evil background tasks after running the command, such as  encrypting your local disk, destroying some files, etc

**Comment by voghDev** [comment]
LOL no way! let's maintain peace above everything! ;-)

**Comment by javilobo8** [comment]
But only if user's IP is in Catalonia :trollface:

**Comment by 0xNacho** [comment]
We coud use ip-api.com to perform this task:

```http://ip-api.com/json/208.80.152.201?callback=yourfunction ```
