### ISSUE TITLE
@jordihurtado

### ISSUE THREAD

**Issue by felipem775** [voghDev/git-pushdemont#16]
¿Qué características?, y sobre todo ¿qué uptime? tiene tu máquina

**Comment by voghDev** [comment]
Buenas,
como ya habrás podido imaginar a raiz del nombre, la característica fundamental y más importante de esta máquina es la inmortalidad

![crop1](https://user-images.githubusercontent.com/4963568/31574999-710a95be-b0dc-11e7-828b-1d9ccdc97db2.jpeg)

Muchos programadores y compañeros de GitHub te pueden corroborar su existencia y su excelente desempeño.
Respecto al uptime lo normal... unos 100 años 

Saludos!
